//! Lint: `ctt_assert_without_message`
//!
//! `assert_eq!(a, b)` and `assert!(cond)` in test code without a failure message
//! produce opaque output when they fail. A message is required in integration
//! tests; strongly recommended in unit tests.
//!
//! Only fires inside `#[test]` / `#[tokio::test]` / `async_test!()` / `test!()`
//! contexts (i.e. when we are inside a `#[cfg(test)]` module or an item with a
//! test attribute).

use clippy_utils::diagnostics::span_lint_and_help;
use rustc_ast::{AttrStyle, Item, ItemKind, MacCall};
use rustc_lint::{EarlyContext, EarlyLintPass};
use rustc_session::{declare_lint, impl_lint_pass};
use rustc_span::Symbol;

declare_lint! {
    /// Detects `assert!`, `assert_eq!`, or `assert_ne!` calls in test code that
    /// do not include a failure message.
    ///
    /// ### Why is this bad?
    ///
    /// A failing assertion without a message prints only the raw values and
    /// gives no context about *what* invariant was violated. This is fine for a
    /// quick unit test, but integration and acceptance tests produce confusing CI
    /// output. Adding a message is low-cost and high-value.
    ///
    /// ### Example (bad)
    ///
    /// ```rust
    /// assert_eq!(result, expected);
    /// ```
    ///
    /// ### Example (good)
    ///
    /// ```rust
    /// assert_eq!(result, expected, "tool call should echo the input unchanged");
    /// ```
    pub ASSERT_WITHOUT_MESSAGE,
    Warn,
    "`assert_eq!` / `assert_ne!` / `assert!` in tests should include a failure message"
}

const ASSERT_MACROS: &[&str] = &["assert", "assert_eq", "assert_ne"];

/// Depth counter for `#[cfg(test)]` modules AND functions carrying a test attribute.
#[derive(Default)]
pub struct AssertWithoutMessage {
    test_depth: u32,
}

impl_lint_pass!(AssertWithoutMessage => [ASSERT_WITHOUT_MESSAGE]);

fn has_test_attr(item: &Item) -> bool {
    item.attrs.iter().any(|attr| {
        if attr.style != AttrStyle::Outer {
            return false;
        }
        // attr.path() returns SmallVec<[Symbol; 1]>
        let path = attr.path();
        match path.len() {
            1 => path[0] == Symbol::intern("test"),
            2 => path[1] == Symbol::intern("test"),
            _ => false,
        }
    })
}

fn is_cfg_test_mod(item: &Item) -> bool {
    if !matches!(item.kind, ItemKind::Mod(..)) {
        return false;
    }
    item.attrs.iter().any(|attr| {
        attr.has_name(Symbol::intern("cfg"))
            && attr
                .meta_item_list()
                .is_some_and(|list| list.iter().any(|mi| mi.has_name(Symbol::intern("test"))))
    })
}

/// Count the number of top-level arguments in a macro call by counting top-level commas.
fn count_macro_args(mac: &MacCall) -> usize {
    use rustc_ast::token::TokenKind;
    use rustc_ast::tokenstream::TokenTree;

    let mut args = 1usize;
    let mut any = false;

    for tree in mac.args.tokens.iter() {
        match tree {
            TokenTree::Token(tok, _) => {
                if tok.kind == TokenKind::Comma {
                    args += 1;
                } else {
                    any = true;
                }
            }
            TokenTree::Delimited(..) => {
                any = true;
            }
        }
    }

    if !any { 0 } else { args }
}

impl EarlyLintPass for AssertWithoutMessage {
    fn check_item(&mut self, _cx: &EarlyContext<'_>, item: &Item) {
        if is_cfg_test_mod(item) || has_test_attr(item) {
            self.test_depth += 1;
        }
    }

    fn check_item_post(&mut self, _cx: &EarlyContext<'_>, item: &Item) {
        if is_cfg_test_mod(item) || has_test_attr(item) {
            self.test_depth = self.test_depth.saturating_sub(1);
        }
    }

    fn check_mac(&mut self, cx: &EarlyContext<'_>, mac: &MacCall) {
        if self.test_depth == 0 {
            return; // not inside test code
        }
        if mac.path.span.from_expansion() {
            return; // generated by test!() or async_test!() — already has context
        }

        let name = mac
            .path
            .segments
            .last()
            .map(|s| s.ident.name.as_str().to_owned())
            .unwrap_or_default();

        if !ASSERT_MACROS.iter().any(|m| *m == name.as_str()) {
            return;
        }

        // Required arg counts:
        //   assert!(cond)          → 1 arg  (needs msg → 2)
        //   assert_eq!(a, b)       → 2 args (needs msg → 3)
        //   assert_ne!(a, b)       → 2 args (needs msg → 3)
        let min_with_msg = if name == "assert" { 2 } else { 3 };
        let actual = count_macro_args(mac);

        if actual < min_with_msg {
            span_lint_and_help(
                cx,
                ASSERT_WITHOUT_MESSAGE,
                mac.path.span,
                format!("`{name}!` in test code is missing a failure message"),
                None,
                format!(
                    "add a message: `{name}!({}, \"description of the invariant\")`",
                    if name == "assert" { "cond" } else { "left, right" }
                ),
            );
        }
    }
}
