//! Lint: `ctt_no_raw_test`
//!
//! A bare `#[test]` attribute on a function bypasses CTT's `test!()` macro, losing:
//! per-test timeouts, AAA tracking, and fixture integration.

use clippy_utils::diagnostics::span_lint_and_help;
use rustc_ast::{AttrStyle, Item, ItemKind};
use rustc_lint::{EarlyContext, EarlyLintPass};
use rustc_session::{declare_lint, impl_lint_pass};
use rustc_span::sym;

declare_lint! {
    /// Detects `#[test]` directly on a function that is not generated by `test!()`.
    ///
    /// ### Why is this bad?
    ///
    /// CTT's `test!()` macro enforces per-test timeouts (1 s default), AAA
    /// structure tracking, and fixture integration. Writing `#[test]` directly
    /// opts out of all of these guarantees silently.
    ///
    /// ### Example (bad)
    ///
    /// ```rust
    /// #[test]
    /// fn raw_test() {
    ///     assert_eq!(1 + 1, 2);
    /// }
    /// ```
    ///
    /// ### Example (good)
    ///
    /// ```rust
    /// use chicago_tdd_tools::prelude::*;
    /// test!(my_test, {
    ///     assert_eq!(1 + 1, 2);
    /// });
    /// ```
    pub NO_RAW_TEST,
    Warn,
    "use `test!()` instead of `#[test]` — raw `#[test]` bypasses CTT timeouts and AAA tracking"
}

pub struct NoRawTest;

impl_lint_pass!(NoRawTest => [NO_RAW_TEST]);

impl EarlyLintPass for NoRawTest {
    fn check_item(&mut self, cx: &EarlyContext<'_>, item: &Item) {
        if !matches!(item.kind, ItemKind::Fn(..)) {
            return;
        }

        // Only flag user-written `#[test]` — macro-generated spans have an expansion context.
        let is_direct_test_attr = item.attrs.iter().any(|attr| {
            attr.style == AttrStyle::Outer
                && attr.has_name(sym::test)
                && !attr.span.from_expansion()
        });

        if is_direct_test_attr {
            span_lint_and_help(
                cx,
                NO_RAW_TEST,
                item.span,
                "`#[test]` bypasses CTT's `test!()` macro — timeouts and AAA tracking are disabled",
                None,
                "replace with `test!(fn_name, { … })` from `chicago_tdd_tools::prelude::*`",
            );
        }
    }
}
